name: Auto Commit Bot

on:
  schedule:
    - cron: "0 0 * * *"   # ⏰ Runs daily at 00:00 UTC
  workflow_dispatch:       # ▶️ Allow manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run daily commits
        run: node index.js

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push
